import OpenAI from "openai";
import { z } from "zod";
import { zodTextFormat } from "openai/helpers/zod";

import { checkTranslationKeepsFacts } from "@/lib/answer-facts";
import type { AnswerLanguage, AssistantAnswer } from "@/lib/types";
import { openAIConfig } from "@/server/config";

const translationSchema = z.object({
  text: z.string().max(4_000),
  periodLabel: z.string().max(200),
});

const LANGUAGE_NAMES: Record<AnswerLanguage, string> = {
  sv: "svenska",
  so: "somaliska",
};

let client: OpenAI | null = null;
let clientKey = "";

function openAI(): { client: OpenAI; model: string } | null {
  const config = openAIConfig();
  if (!config) return null;
  if (!client || clientKey !== config.apiKey) {
    client = new OpenAI({ apiKey: config.apiKey });
    clientKey = config.apiKey;
  }
  return { client, model: config.model };
}

/**
 * Render an already-computed answer in the language the question was asked in.
 *
 * The answer is never generated by the model, only restated. Names, titles,
 * dates and times must survive verbatim, and a check enforces that: if anything
 * a family member could act on went missing, the Swedish answer is returned
 * unchanged. A wrong time in a language you understand is worse than a right
 * time in one you have to work at.
 */
export async function translateAnswer(
  answer: AssistantAnswer,
  language: AnswerLanguage | undefined,
): Promise<AssistantAnswer> {
  if (!language || language === "sv") return answer;
  if (!answer.text.trim()) return answer;

  const ai = openAI();
  if (!ai) return answer;

  try {
    const response = await ai.client.responses.parse({
      model: ai.model,
      store: false,
      input: [
        {
          role: "system",
          content: [
            `Översätt en färdig kalendersammanfattning till ${LANGUAGE_NAMES[language]}.`,
            "Du får inte lägga till, ta bort eller ändra någon uppgift.",
            "Behåll alla siffror, klockslag, datum och tidsintervall exakt som de står.",
            "Behåll personnamn och titlar på kalenderposter oöversatta, inklusive citattecken.",
            "Svara endast med översättningen.",
          ].join(" "),
        },
        {
          role: "user",
          content: JSON.stringify({ text: answer.text, periodLabel: answer.periodLabel }),
        },
      ],
      text: { format: zodTextFormat(translationSchema, "translated_answer") },
    });

    const parsed = response.output_parsed;
    if (!parsed) return answer;

    const check = checkTranslationKeepsFacts(answer.text, parsed.text);
    if (!check.ok) return answer;

    return { ...answer, text: parsed.text.trim(), periodLabel: parsed.periodLabel.trim() || answer.periodLabel };
  } catch {
    // A failed translation must never cost the family their answer.
    return answer;
  }
}
